print ("First Timestamp")
hour1 = input("Enter Hours: ")
min1 = input("Enter Minutes: ")
sec1 = input("Enter Seconds: ")
print ("Second Timestamp")
hour2 = input("Enter Hours: ")
min2 = input("Enter Minutes: ")
sec2 = input("Enter Seconds: ")
hourfin = ((int(hour2) - int(hour1)) * 3600)
minfin = ((int(min2) - int(min1)) * 60)
secfin = (int(sec2) - int(sec1))
print (int(hourfin) + int(minfin) + int(secfin))