num = input("Enter a number: ")
nextnum = (int(num) + 1)
prevnum = (int(num) - 1)
print ("The next number for the number " + str(num) + " is " + str(nextnum))
print ("The previous number for the number " + str(num) + " is " + str(prevnum))